name: makeplans
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.4.1
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.5
  firebase_core: ^3.13.0
  intl: ^0.18.1
  flutter_typeahead: ^4.3.7
  razorpay_flutter: ^1.3.5
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0


  pdf: ^3.6.0
  printing: ^5.0.0



  flutter_dotenv: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.3.0
  geolocator: ^13.0.4
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # ✅ Corrected Assets Section
  assets:
    - assets/images/logo.png
#    - assets/images/taj_palace.jpeg
#    - assets/images/itc_grand_chola.jpeg
#    - assets/images/leela_palace.jpeg

    - assets/images/facebook.png
    #    - assets/images/apple.png
    #    - assets/images/background.png
    - assets/images/google.png
    - .env